- name: Xubuntu 24.4 セットアップ
  hosts: localhost
  become: true

  tasks:
    - name: aptパッケージの更新とアップグレード
      apt:
        update_cache: yes
        upgrade: dist

    - name: 共通パッケージのインストール
      apt:
        name:
          - curl
          - git
          - vim
          - htop
        state: present

    - name: XFCE用ツールのインストール
      apt:
        name:
          - xfce4-terminal
          - xfce4-screenshooter
        state: present

    - name: Mozc日本語入力のインストール
      apt:
        name:
          - ibus-mozc
        state: present

    - name: ibusの再起動
      command: ibus-daemon -r -d -x

    - name: WineHQ用ディレクトリの作成
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: WineHQキーのダウンロードと保存
      get_url:
        url: https://dl.winehq.org/wine-builds/winehq.key
        dest: /etc/apt/keyrings/winehq-archive.key
        mode: '0644'
      register: winehq_key

    - name: WineHQキーをdearmor形式に変換
      command: gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key /etc/apt/keyrings/winehq-archive.key
      when: winehq_key is changed

    - name: WineHQソースリストのダウンロード
      get_url:
        url: https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
        dest: /etc/apt/sources.list.d/winehq-noble.sources
        mode: '0644'

    - name: aptパッケージリストの更新
      apt:
        update_cache: yes

    - name: WineHQ安定版のインストール
      apt:
        name: winehq-stable
        state: present
        install_recommends: yes

    - name: Wine Geckoインストーラー用ディレクトリの作成
      file:
        path: /usr/share/wine/gecko
        state: directory
        mode: '0755'

    - name: Wine Geckoインストーラー（64ビット）のダウンロード
      get_url:
        url: https://dl.winehq.org/wine/wine-gecko/2.47.1/wine-gecko-2.47.1-x86_64.msi 
        dest: /usr/share/wine/gecko/wine-gecko-2.47.1-x86_64.msi
        mode: '0644'

    - name: Wine Gecko（64ビット）のインストール
      command: wine64 /usr/share/wine/gecko/wine-gecko-2.47.1-x86_64.msi
      become_user: "{{ ansible_user }}"
      environment:
        WINEPREFIX: /home/{{ ansible_user }}/.wine64

    - name: Google Chromeリポジトリキーの追加
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Google Chromeリポジトリの追加
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Google Chromeのインストール
      apt:
        name: google-chrome-stable
        state: present

    - name: Microsoft GPGキーの追加
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Visual Studio Codeリポジトリの追加
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
        state: present

    - name: Visual Studio Codeのインストール
      apt:
        name: code
        state: present

    - name: 不要なパッケージのクリーンアップ
      apt:
        autoremove: yes
        autoclean: yes

    - name: Copilot拡張のインストール用ディレクトリ作成
      file:
        path: /home/{{ ansible_user }}/.config/google-chrome/Default/Extensions/eodojedcgoicpkfcjkhghafoadllibab
        state: directory
        mode: '0755'

    - name: Copilot拡張のダウンロード
      get_url:
        url: https://clients2.google.com/service/update2/crx?response=redirect&prodversion=91.0.4472.124&x=id%3Deodojedcgoicpkfcjkhghafoadllibab%26installsource%3Dondemand%26uc
        dest: /home/{{ ansible_user }}/.config/google-chrome/Default/Extensions/eodojedcgoicpkfcjkhghafoadllibab/copilot_extension.crx
        mode: '0644'

    - name: Copilot拡張を解凍
      unarchive:
        src: /home/{{ ansible_user }}/.config/google-chrome/Default/Extensions/eodojedcgoicpkfcjkhghafoadllibab/copilot_extension.crx
        dest: /home/{{ ansible_user }}/.config/google-chrome/Default/Extensions/eodojedcgoicpkfcjkhghafoadllibab/
        remote_src: yes
